<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
?>

<?php echo $this->form()->openTag($form)?>

<dl class="zend_form">
          <?php echo $this->formElementErrors($form->get('identity'))?>

	<div id="contenedor-campos">
		<div id="texto-usuario"><?php echo $this->formLabel($form->get('identity')) ?></div>
		<div id="campos">
			<?php echo $this->formInput($form->get('identity'))?>
		</div>
		<div id="texto-contrasenna"><?php echo $this->formLabel($form->get('credential')) ?></div>
		<div id="campos">
			<?php echo $this->formInput($form->get('credential'))?>
		</div>
		<?php if ($this->redirect): ?>
            <input type="hidden" name="redirect"
			value="<?php echo $this->escapeHtml($this->redirect) ?>" />
        <?php endif ?>
        <input type="hidden" name="sourceRouteLogin"
			value="<?php echo $this->escapeHtml($this->sourceRouteLogin) ?>" />
		<div id="btn-entrar">
			<?php echo $this->formButton($form->get('submit'))?>
		</div>
	</div>

	   <div style="height: 20px"> </div>
</dl>

<?php echo $this->form()->closeTag() ?>